import React from "react";

import Search from "../components/Search";
import img from '../assets/Lot1.jpg';

import A1img from '../assets/Lot2.jpg'
import A2img from '../assets/Lot3.jpg'
import A3img from '../assets/Lot4.jpg'
import '../components/css/blog_expanded.css'
import '../components/css/Blog.css'
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { NavLink } from "react-router-dom";


const Lotus = () => {
  return (
    <div>
        <div className="main">
        <Navbar />
    <div className='blog_leftside' style={{width : "65%",float : "left"}}>
    <div className="main-wrapper-boxed">
        <center><img src={img} alt=''></img></center>
        <h1>A Flight To The Marvelous World Of Akshardham Temple</h1>
        <h2>The Lotus Temple, located in New Delhi, India, is a Baháʼí House of Worship that was dedicated in December 1986. Notable for its lotus-like shape, it has become a prominent attraction in the city. Like all Bahá’í Houses of Worship, the Lotus Temple is open to all, regardless of religion or any other qualification.The building is composed of 27 free-standing marble-clad "petals" arranged in clusters of three to form nine sides,with nine doors opening onto a central hall with a height of slightly over 34 metres and a capacity of 1,300 people.The Lotus Temple has won numerous architectural awards and has been featured in many newspaper and magazine articles.</h2>
        <div className="vertical"></div>
        <b>Rúhíyyih Khánum laid the foundation stone for the Lotus Temple on 19 October 1977 and dedicated the temple on 24 December 1986.For the dedication, there was a gathering of 8,000 Baháʼís from 107 countries, including some 4,000 Baháʼís from 22 states in India.The temple was opened to the public on 1 January 1987 and more than 10,000 people visited that day.</b><br /><br /><br /><br /><br /><br /><br /> <br /><br /><br /><br /><br /><br />
        <h2>The Lotus Temple is situated near the Kalkaji Mandir metro station about 500 metres away.It is in the village of Bahapur in New Delhi, National Capital Territory of Delhi, near Nehru Place and lies on the western bank of the Yamuna River.
Of the temple's total electricity use of 500 kilowatts (kW), 120 kW is provided by solar power generated by solar panels on the building.This saves the temple ₹120,000 per month.It is the first temple in Delhi to use solar power.
As is the case with other stone monuments such as the Taj Mahal, the Lotus Temple is becoming discoloured due to air pollution in India. Specifically, the white marble is turning grey and yellow due to pollution from vehicles and manufacturing in the city, among other sources.</h2>
        <img src={A1img} alt='' className='A1'></img>
        <img src={A2img} alt='' className='A2'></img>
        <img src={A3img} alt='' className='A3'></img>
        <NavLink to="/blog" className="readless">READ LESS</NavLink>
        </div>
    </div>
    <div className='blog_rightside' style={{width : "30%", height : "575px",float : "left"}}>
        <Search />
    </div>
    </div>
    <Footer />
    </div>
    
  );
}

export default Lotus;